/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables;


import com.luzhiqing.bamboo.constants.converter.ExpressCompanyConverter;
import com.luzhiqing.bamboo.constants.converter.OrderTypeConverter;
import com.luzhiqing.bamboo.constants.enums.ExpressCompanyType;
import com.luzhiqing.bamboo.constants.enums.OrderType;
import com.luzhiqing.bamboo.entity.Dev;
import com.luzhiqing.bamboo.entity.Indexes;
import com.luzhiqing.bamboo.entity.Keys;
import com.luzhiqing.bamboo.entity.tables.records.TExpressOrderRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TExpressOrder extends TableImpl<TExpressOrderRecord> {

    private static final long serialVersionUID = -1449134878;

    /**
     * The reference instance of <code>dev.t_express_order</code>
     */
    public static final TExpressOrder T_EXPRESS_ORDER = new TExpressOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TExpressOrderRecord> getRecordType() {
        return TExpressOrderRecord.class;
    }

    /**
     * The column <code>dev.t_express_order.id</code>.
     */
    public final TableField<TExpressOrderRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>dev.t_express_order.user_id</code>.
     */
    public final TableField<TExpressOrderRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev.t_express_order.express_number</code>.
     */
    public final TableField<TExpressOrderRecord, String> EXPRESS_NUMBER = createField("express_number", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.express_company_name</code>.
     */
    public final TableField<TExpressOrderRecord, String> EXPRESS_COMPANY_NAME = createField("express_company_name", org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.express_company</code>.
     */
    public final TableField<TExpressOrderRecord, ExpressCompanyType> EXPRESS_COMPANY = createField("express_company", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "", new ExpressCompanyConverter());

    /**
     * The column <code>dev.t_express_order.phone</code>.
     */
    public final TableField<TExpressOrderRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.address</code>.
     */
    public final TableField<TExpressOrderRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(2014).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.student_name</code>.
     */
    public final TableField<TExpressOrderRecord, String> STUDENT_NAME = createField("student_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.access_day</code>.
     */
    public final TableField<TExpressOrderRecord, LocalDateTime> ACCESS_DAY = createField("access_day", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>dev.t_express_order.access_number</code>.
     */
    public final TableField<TExpressOrderRecord, String> ACCESS_NUMBER = createField("access_number", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.order_type</code>.
     */
    public final TableField<TExpressOrderRecord, OrderType> ORDER_TYPE = createField("order_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "", new OrderTypeConverter());

    /**
     * The column <code>dev.t_express_order.order_type_name</code>.
     */
    public final TableField<TExpressOrderRecord, String> ORDER_TYPE_NAME = createField("order_type_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.remark</code>.
     */
    public final TableField<TExpressOrderRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR(2048).nullable(false).defaultValue(DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev.t_express_order.create_time</code>.
     */
    public final TableField<TExpressOrderRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>dev.t_express_order.create_user</code>.
     */
    public final TableField<TExpressOrderRecord, Integer> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev.t_express_order.create_user_name</code>.
     */
    public final TableField<TExpressOrderRecord, String> CREATE_USER_NAME = createField("create_user_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>dev.t_express_order.update_time</code>.
     */
    public final TableField<TExpressOrderRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>dev.t_express_order.update_user</code>.
     */
    public final TableField<TExpressOrderRecord, Integer> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>dev.t_express_order.update_user_name</code>.
     */
    public final TableField<TExpressOrderRecord, String> UPDATE_USER_NAME = createField("update_user_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>dev.t_express_order.delete_time</code>.
     */
    public final TableField<TExpressOrderRecord, LocalDateTime> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>dev.t_express_order.delete_user</code>.
     */
    public final TableField<TExpressOrderRecord, Integer> DELETE_USER = createField("delete_user", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>dev.t_express_order.delete_user_name</code>.
     */
    public final TableField<TExpressOrderRecord, String> DELETE_USER_NAME = createField("delete_user_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>dev.t_express_order.enabled</code>.
     */
    public final TableField<TExpressOrderRecord, Byte> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>dev.t_express_order.data_version</code>.
     */
    public final TableField<TExpressOrderRecord, LocalDateTime> DATA_VERSION = createField("data_version", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>dev.t_express_order</code> table reference
     */
    public TExpressOrder() {
        this(DSL.name("t_express_order"), null);
    }

    /**
     * Create an aliased <code>dev.t_express_order</code> table reference
     */
    public TExpressOrder(String alias) {
        this(DSL.name(alias), T_EXPRESS_ORDER);
    }

    /**
     * Create an aliased <code>dev.t_express_order</code> table reference
     */
    public TExpressOrder(Name alias) {
        this(alias, T_EXPRESS_ORDER);
    }

    private TExpressOrder(Name alias, Table<TExpressOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private TExpressOrder(Name alias, Table<TExpressOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dev.DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_EXPRESS_ORDER_IX_ACCESS_NUMBER, Indexes.T_EXPRESS_ORDER_IX_EXPRESS_NUMBER, Indexes.T_EXPRESS_ORDER_IX_PHONE, Indexes.T_EXPRESS_ORDER_IX_USER_ID, Indexes.T_EXPRESS_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TExpressOrderRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_EXPRESS_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TExpressOrderRecord> getPrimaryKey() {
        return Keys.KEY_T_EXPRESS_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TExpressOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<TExpressOrderRecord>>asList(Keys.KEY_T_EXPRESS_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TExpressOrder as(String alias) {
        return new TExpressOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TExpressOrder as(Name alias) {
        return new TExpressOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TExpressOrder rename(String name) {
        return new TExpressOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TExpressOrder rename(Name name) {
        return new TExpressOrder(name, null);
    }
}
