server:
  port: 8083
app:
  id: bamboo-biz-server
apollo:
  bootstrap:
    enabled: true
    namespaces: bamboo
  config-service: http://82.157.100.36:8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://82.157.100.36:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: ${app.id}
spring:
  profiles:
    active: bamboo
