/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.pojos;


import com.luzhiqing.bamboo.constants.enums.ExpressCompanyType;
import com.luzhiqing.bamboo.constants.enums.OrderType;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TExpressOrder implements Serializable {

    private static final long serialVersionUID = -244441136;

    private Integer            id;
    private Integer            userId;
    private String             expressNumber;
    private String             expressCompanyName;
    private ExpressCompanyType expressCompany;
    private String             phone;
    private String             address;
    private String             studentName;
    private LocalDateTime      accessDay;
    private String             accessNumber;
    private OrderType          orderType;
    private String             orderTypeName;
    private String             remark;
    private LocalDateTime      createTime;
    private Integer            createUser;
    private String             createUserName;
    private LocalDateTime      updateTime;
    private Integer            updateUser;
    private String             updateUserName;
    private LocalDateTime      deleteTime;
    private Integer            deleteUser;
    private String             deleteUserName;
    private Byte               enabled;
    private LocalDateTime      dataVersion;

    public TExpressOrder() {}

    public TExpressOrder(TExpressOrder value) {
        this.id = value.id;
        this.userId = value.userId;
        this.expressNumber = value.expressNumber;
        this.expressCompanyName = value.expressCompanyName;
        this.expressCompany = value.expressCompany;
        this.phone = value.phone;
        this.address = value.address;
        this.studentName = value.studentName;
        this.accessDay = value.accessDay;
        this.accessNumber = value.accessNumber;
        this.orderType = value.orderType;
        this.orderTypeName = value.orderTypeName;
        this.remark = value.remark;
        this.createTime = value.createTime;
        this.createUser = value.createUser;
        this.createUserName = value.createUserName;
        this.updateTime = value.updateTime;
        this.updateUser = value.updateUser;
        this.updateUserName = value.updateUserName;
        this.deleteTime = value.deleteTime;
        this.deleteUser = value.deleteUser;
        this.deleteUserName = value.deleteUserName;
        this.enabled = value.enabled;
        this.dataVersion = value.dataVersion;
    }

    public TExpressOrder(
        Integer            id,
        Integer            userId,
        String             expressNumber,
        String             expressCompanyName,
        ExpressCompanyType expressCompany,
        String             phone,
        String             address,
        String             studentName,
        LocalDateTime      accessDay,
        String             accessNumber,
        OrderType          orderType,
        String             orderTypeName,
        String             remark,
        LocalDateTime      createTime,
        Integer            createUser,
        String             createUserName,
        LocalDateTime      updateTime,
        Integer            updateUser,
        String             updateUserName,
        LocalDateTime      deleteTime,
        Integer            deleteUser,
        String             deleteUserName,
        Byte               enabled,
        LocalDateTime      dataVersion
    ) {
        this.id = id;
        this.userId = userId;
        this.expressNumber = expressNumber;
        this.expressCompanyName = expressCompanyName;
        this.expressCompany = expressCompany;
        this.phone = phone;
        this.address = address;
        this.studentName = studentName;
        this.accessDay = accessDay;
        this.accessNumber = accessNumber;
        this.orderType = orderType;
        this.orderTypeName = orderTypeName;
        this.remark = remark;
        this.createTime = createTime;
        this.createUser = createUser;
        this.createUserName = createUserName;
        this.updateTime = updateTime;
        this.updateUser = updateUser;
        this.updateUserName = updateUserName;
        this.deleteTime = deleteTime;
        this.deleteUser = deleteUser;
        this.deleteUserName = deleteUserName;
        this.enabled = enabled;
        this.dataVersion = dataVersion;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getExpressNumber() {
        return this.expressNumber;
    }

    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber;
    }

    public String getExpressCompanyName() {
        return this.expressCompanyName;
    }

    public void setExpressCompanyName(String expressCompanyName) {
        this.expressCompanyName = expressCompanyName;
    }

    public ExpressCompanyType getExpressCompany() {
        return this.expressCompany;
    }

    public void setExpressCompany(ExpressCompanyType expressCompany) {
        this.expressCompany = expressCompany;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getStudentName() {
        return this.studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public LocalDateTime getAccessDay() {
        return this.accessDay;
    }

    public void setAccessDay(LocalDateTime accessDay) {
        this.accessDay = accessDay;
    }

    public String getAccessNumber() {
        return this.accessNumber;
    }

    public void setAccessNumber(String accessNumber) {
        this.accessNumber = accessNumber;
    }

    public OrderType getOrderType() {
        return this.orderType;
    }

    public void setOrderType(OrderType orderType) {
        this.orderType = orderType;
    }

    public String getOrderTypeName() {
        return this.orderTypeName;
    }

    public void setOrderTypeName(String orderTypeName) {
        this.orderTypeName = orderTypeName;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Integer getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    public String getCreateUserName() {
        return this.createUserName;
    }

    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    public String getUpdateUserName() {
        return this.updateUserName;
    }

    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName;
    }

    public LocalDateTime getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(LocalDateTime deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteUser() {
        return this.deleteUser;
    }

    public void setDeleteUser(Integer deleteUser) {
        this.deleteUser = deleteUser;
    }

    public String getDeleteUserName() {
        return this.deleteUserName;
    }

    public void setDeleteUserName(String deleteUserName) {
        this.deleteUserName = deleteUserName;
    }

    public Byte getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    public LocalDateTime getDataVersion() {
        return this.dataVersion;
    }

    public void setDataVersion(LocalDateTime dataVersion) {
        this.dataVersion = dataVersion;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TExpressOrder (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(expressNumber);
        sb.append(", ").append(expressCompanyName);
        sb.append(", ").append(expressCompany);
        sb.append(", ").append(phone);
        sb.append(", ").append(address);
        sb.append(", ").append(studentName);
        sb.append(", ").append(accessDay);
        sb.append(", ").append(accessNumber);
        sb.append(", ").append(orderType);
        sb.append(", ").append(orderTypeName);
        sb.append(", ").append(remark);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUser);
        sb.append(", ").append(createUserName);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(updateUserName);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deleteUser);
        sb.append(", ").append(deleteUserName);
        sb.append(", ").append(enabled);
        sb.append(", ").append(dataVersion);

        sb.append(")");
        return sb.toString();
    }
}
