create table t_express_order(
    id                            int(11) not null auto_increment,
    user_id                       int(11) not null default '0',
    express_number                varchar(64) not null default '',
    express_company_name          varchar(512) not null default '',
    express_company               int(1) not null default '0',
    phone                         varchar(20) not null default '',
    address                       varchar(2014) not null default '',
    student_name                  varchar(64) not null default '',
    access_day                    datetime  not null default current_timestamp,
    access_number                 varchar(64) not null default '',
    order_type                    int(1) not null default '0',
    order_type_name               varchar(64) not null default '',
    remark                        varchar(2048) not null default '',
    create_time                   datetime not null,
    create_user                   int(11) not null,
    create_user_name              varchar(64) not null,
    update_time                   datetime,
    update_user                   int(11),
    update_user_name              varchar(64),
    delete_time                   datetime,
    delete_user                   int(11),
    delete_user_name              varchar(64),
    enabled                       tinyint(1) not null default '1',
    data_version                  timestamp not null default current_timestamp,
    primary key(`id`),
    key ix_user_id(`user_id`),
    key ix_express_number(`express_number`),
    key ix_phone(`phone`),
    key ix_access_number(`access_number`)
)engine=innodb auto_increment=1 default charset=utf8mb4