/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity;


import com.luzhiqing.bamboo.entity.tables.TExpressOrder;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>dev</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_EXPRESS_ORDER_IX_ACCESS_NUMBER = Indexes0.T_EXPRESS_ORDER_IX_ACCESS_NUMBER;
    public static final Index T_EXPRESS_ORDER_IX_EXPRESS_NUMBER = Indexes0.T_EXPRESS_ORDER_IX_EXPRESS_NUMBER;
    public static final Index T_EXPRESS_ORDER_IX_PHONE = Indexes0.T_EXPRESS_ORDER_IX_PHONE;
    public static final Index T_EXPRESS_ORDER_IX_USER_ID = Indexes0.T_EXPRESS_ORDER_IX_USER_ID;
    public static final Index T_EXPRESS_ORDER_PRIMARY = Indexes0.T_EXPRESS_ORDER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_EXPRESS_ORDER_IX_ACCESS_NUMBER = Internal.createIndex("ix_access_number", TExpressOrder.T_EXPRESS_ORDER, new OrderField[] { TExpressOrder.T_EXPRESS_ORDER.ACCESS_NUMBER }, false);
        public static Index T_EXPRESS_ORDER_IX_EXPRESS_NUMBER = Internal.createIndex("ix_express_number", TExpressOrder.T_EXPRESS_ORDER, new OrderField[] { TExpressOrder.T_EXPRESS_ORDER.EXPRESS_NUMBER }, false);
        public static Index T_EXPRESS_ORDER_IX_PHONE = Internal.createIndex("ix_phone", TExpressOrder.T_EXPRESS_ORDER, new OrderField[] { TExpressOrder.T_EXPRESS_ORDER.PHONE }, false);
        public static Index T_EXPRESS_ORDER_IX_USER_ID = Internal.createIndex("ix_user_id", TExpressOrder.T_EXPRESS_ORDER, new OrderField[] { TExpressOrder.T_EXPRESS_ORDER.USER_ID }, false);
        public static Index T_EXPRESS_ORDER_PRIMARY = Internal.createIndex("PRIMARY", TExpressOrder.T_EXPRESS_ORDER, new OrderField[] { TExpressOrder.T_EXPRESS_ORDER.ID }, true);
    }
}
