/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity;


import com.luzhiqing.bamboo.entity.tables.TExpressOrder;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dev
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dev.t_express_order</code>.
     */
    public static final TExpressOrder T_EXPRESS_ORDER = TExpressOrder.T_EXPRESS_ORDER;
}
